name: CI
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'trunk'

      - run: node --version
      - run: yarn --frozen-lockfile
      - run: yarn nx workspace-lint
      - run: yarn nx format:check
      - run: yarn nx affected --target=lint --parallel=3
      - run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      - run: yarn nx affected --target=build --parallel=3
